### PR TITLE
Keep token counts

### PR DESCRIPTION
**Pull request by irgolic**
Transplanted from https://github.com/ShreyaR/guardrails/pull/287

This PR refactors the LLM callable wrappers to subclasses instead of function wrappers, and defines an LLMResponse object that allows returning tracking for the number of tokens used (implemented in openai).

### CODE REVIEW

**Comment by CalebCourier** [comment]
Can we get additional test coverage on this?

**Comment by irgolic** [comment]
The changes that fell out of coverage are the LLM callable subclasses, which we're mocking (so they never get run). I think it's lower coverage because the function wrappers (also mocked and not run) were written with less lines of code.

**Review by CalebCourier — COMMENTED** [review]
If I'm reading this right, the outputs to the user from `__call__` and `parse` all stay the same, we're just now adding extra properties to the state via the guard logs to track token counts in and out when applicable?

I also ran a few tests where I pass in a custom llm function and there are no regressions there so nicely done!

**Comment by CalebCourier** [comment]
> The changes that fell out of coverage are the LLM callable subclasses, which we're mocking (so they never get run). I think it's lower coverage because the function wrappers (also mocked and not run) were written with less lines of code.

Can we add some unit tests on the LLM callable subclasses then?  We need unit tests on `llm_providers.py` in general so testing the changes here would be a good start.  We just shouldn't have decreasing coverage going forward.

**Comment by CalebCourier** [comment]
Was working on tweaking our exception handling in the PromptCallable classes to allow tenacity to perform retries for us and based off of your branch for that to avoid merge conflicts.  Found a couple places where asyncs weren't being awaited and added some tests around the `ArbitraryCallable` and `AsyncArbitraryCallable` classes which should also hit their base classes where the exception handling happens.  I'm going to PR against this branch and that should put us in a good spot for test coverage.

[Edit]: Add PR link: https://github.com/irgolic/guardrails/pull/1

**Comment by irgolic** [comment]
> If I'm reading this right, the outputs to the user from __call__ and parse all stay the same, we're just now adding extra properties to the state via the guard logs to track token counts in and out when applicable?

That's correct.

> Can we add some unit tests on the LLM callable subclasses then?

You're right, I agree they're necessary here. Thanks for the PR!

**Review by CalebCourier — APPROVED** [review]
LGTM!  Should probably get another set of eyes since we both have changes in this PR now.

@zsimjee or @ShreyaR Could one of you take a quick look at this combined changeset please?

**Review by zsimjee — APPROVED** [review]

**Pull request merged**
